### ISSUE TITLE
relax config requiremment

### ISSUE THREAD

**Issue by nsheff** [epigen/pypiper#59]
pypiper current requires args to have `config`, but it shouldn't require this

```
Change status from initializing to running
Traceback (most recent call last):
  File "/sfs/nfs/blue/ns5bc/code/sratofastq/sra_convert.py", line 58, in <module>
    main(sys.argv[1:])
  File "/sfs/nfs/blue/ns5bc/code/sratofastq/sra_convert.py", line 45, in main
    args=args)
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/pypiper/pypiper.py", line 182, in __init__
    if args and args.config_file is not None:
AttributeError: 'Namespace' object has no attribute 'config_file'
```

**Comment by vreuter** [comment]
Patch is included in https://github.com/epigen/pypiper/pull/55
